# Generated by Django 5.0.1 on 2024-01-20 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('school_year', models.CharField(choices=[('First_class', 'First_class'), ('Second_class', 'Second_class'), ('Last_class', 'Last_class')], default='First_class', max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('approval_status', models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PD', max_length=50)),
                ('National_ID', models.IntegerField(help_text='Enter a 14-digit National ID.', unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='SecondClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('OOP', 'OOP'), ('Data Structures', 'Data Structures'), ('Python', 'Python'), ('Network', 'Network')], max_length=50)),
                ('school_year', models.CharField(choices=[('First_class', 'First_class'), ('Second_class', 'Second_class'), ('Last_class', 'Last_class')], max_length=50)),
                ('approval_status', models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PD', max_length=50)),
                ('students', models.ManyToManyField(related_name='second_class_rooms', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='LastClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('Java Script', 'Java Script'), ('Websockets', 'Websockets'), ('Database', 'Database'), ('UI-UX', 'UI-UX')], max_length=50)),
                ('school_year', models.CharField(choices=[('First_class', 'First_class'), ('Second_class', 'Second_class'), ('Last_class', 'Last_class')], max_length=50)),
                ('approval_status', models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PD', max_length=50)),
                ('students', models.ManyToManyField(related_name='last_class_rooms', to='school.student')),
            ],
        ),
        migrations.CreateModel(
            name='FirstClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('Operating System', 'Operating System'), ('Data Structures', 'Data Structures'), ('Design Patterns', 'Design Patterns'), ('C++', 'C++')], max_length=50)),
                ('school_year', models.CharField(choices=[('First_class', 'First_class'), ('Second_class', 'Second_class'), ('Last_class', 'Last_class')], max_length=50)),
                ('approval_status', models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PD', max_length=50)),
                ('students', models.ManyToManyField(related_name='first_class_rooms', to='school.student')),
            ],
        ),
    ]
