# Generated by Django 5.0.1 on 2024-01-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='approval_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PD', max_length=50),
        ),
    ]
