# Generated by Django 5.0.1 on 2024-01-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstclassroom',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='lastclassroom',
            name='room',
            field=models.CharField(choices=[('Operating System', 'Operating System'), ('Data Structures', 'Data Structures'), ('Design Patterns', 'Design Patterns'), ('C++', 'C++')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lastclassroom',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AlterField(
            model_name='secondclassroom',
            name='room',
            field=models.CharField(choices=[('Operating System', 'Operating System'), ('Data Structures', 'Data Structures'), ('Design Patterns', 'Design Patterns'), ('C++', 'C++')], max_length=50),
        ),
        migrations.AlterField(
            model_name='secondclassroom',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
    ]
