# Generated by Django 5.0.1 on 2024-01-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstclassroom',
            name='approval_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PD', max_length=50),
        ),
        migrations.AddField(
            model_name='lastclassroom',
            name='approval_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PD', max_length=50),
        ),
        migrations.AddField(
            model_name='secondclassroom',
            name='approval_status',
            field=models.CharField(choices=[('PD', 'Pending'), ('RJ', 'Rejected'), ('AP', 'Approved')], default='PD', max_length=50),
        ),
    ]
