# Generated by Django 5.0.1 on 2024-01-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_firstclassroom_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstclassroom',
            name='students',
            field=models.ManyToManyField(related_name='first_class_rooms', to='school.student'),
        ),
        migrations.AlterField(
            model_name='lastclassroom',
            name='room',
            field=models.CharField(choices=[('Java Script', 'Java Script'), ('Websockets', 'Websockets'), ('Database', 'Database'), ('UI-UX', 'UI-UX')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lastclassroom',
            name='students',
            field=models.ManyToManyField(related_name='last_class_rooms', to='school.student'),
        ),
        migrations.AlterField(
            model_name='secondclassroom',
            name='room',
            field=models.CharField(choices=[('OOP', 'OOP'), ('Data Structures', 'Data Structures'), ('Python', 'Python'), ('Network', 'Network')], max_length=50),
        ),
        migrations.AlterField(
            model_name='secondclassroom',
            name='students',
            field=models.ManyToManyField(related_name='second_class_rooms', to='school.student'),
        ),
    ]
